Repository enormora/packtory, pull requests merged in 2024-02, with the labels that each got.

#37 Add "upgrade" label to Renovate pull requests
  renovate.json
Labels: upgrade

#38 Check pull request labels
  .github/workflows/check-labels.yml
Labels: build

#39 Change automerge type to "pull request"
  renovate.json
Labels: upgrade

#41 Keep track of executable file flags
  integration-tests/publisher/publish.test.ts
  package-lock.json
  package.json
  source/artifacts/artifacts-builder.test.ts
  source/artifacts/artifacts-builder.ts
  source/artifacts/file-manager.test.ts
  source/artifacts/file-manager.ts
  source/dependency-scanner/scanner.test.ts
  source/dependency-scanner/scanner.ts
  source/dependency-scanner/source-file-references.ts
  source/dependency-scanner/source-map-file-locator.test.ts
  source/dependency-scanner/source-map-file-locator.ts
  source/dependency-scanner/typescript-file-host.ts
  source/dependency-scanner/typescript-project-analyzer.test.ts
  source/dependency-scanner/typescript-project-analyzer.ts
  source/file-description/compare.test.ts
  source/file-description/equal.ts
  source/file-description/file-description.ts
  source/file-description/permissions.test.ts
  source/file-description/permissions.ts
  source/packages/command-line-interface/command-line-interface.entry-point.ts
  source/publisher/extract-package-tarball.test.ts
  source/publisher/extract-package-tarball.ts
  source/tar/extract-tar.test.ts
  source/tar/tarball-builder.test.ts
  source/tar/tarball-builder.ts
Labels: enhancement

#42 Keep hashbang lines in substituted contents
  source/source-modifier/import-paths.test.ts
  source/source-modifier/import-paths.ts
Labels: enhancement

#44 Group @enormora/eslint-config dependencies in Renovate updates
  renovate.json
Labels: upgrade

#43 Ignore integration-tests/ directory for dependency updates
  renovate.json
Labels: upgrade
